language: generic
dist: bionic
cache: packages

install:
  # Go, from https://tecadmin.net/install-go-on-ubuntu/
  - wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
  - sudo tar -xf go1.12.7.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOROOT=/usr/local/go
  - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  # Singularity
  - sudo ./install_dependencies.sh
  - go version
  - which go
  - sudo ./install_singularity.sh
  - singularity --version

script:
  # Build the container
  - sudo ./build_container.sh
  # Run the container
  - ./singularity_example_6.sif &
  - sleep 5

